name: Build Docker images, push to Docker Hub & deploy to Google Cloud Run

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Get the tag
        id: get_tag_name
        run: echo ::set-output name=GIT_TAG_NAME::${GITHUB_REF/refs\/tags\//}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            louis030195/codex-code-translation-server:latest
            louis030195/codex-code-translation-server:${{ steps.get_tag_name.outputs.GIT_TAG_NAME}}
            ghcr.io/louis030195/codex-code-translation-server:latest
            ghcr.io/louis030195/codex-code-translation-server:${{ steps.get_tag_name.outputs.GIT_TAG_NAME}}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./client
          file: ./client/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            louis030195/codex-code-translation-client:latest
            louis030195/codex-code-translation-client:${{ steps.get_tag_name.outputs.GIT_TAG_NAME}}
            ghcr.io/louis030195/codex-code-translation-client:latest
            ghcr.io/louis030195/codex-code-translation-client:${{ steps.get_tag_name.outputs.GIT_TAG_NAME}}
      - uses: google-github-actions/setup-gcloud@master
      - 
        name: Turn svc into base64
        run: |
          echo "GCP_SA_KEY_AS_BASE64=$(echo '${{ secrets.GCP_SA_KEY }}' | python -m base64)" >> $GITHUB_ENV
      - 
        uses: RafikFarhad/push-to-gcr-github-action@v4
        with:
          gcloud_service_key: ${{ env.GCP_SA_KEY_AS_BASE64 }}
          registry: gcr.io
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          image_name: codex-code-translation
          image_tag: ${{ steps.get_tag_name.outputs.GIT_TAG_NAME}}
          dockerfile: ./server/Dockerfile
      - 
        name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: codex-code-translation
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          region: europe-west3          
          image: gcr.io/louis030195/codex-code-translation-server
          credentials: ${{ secrets.GCP_SA_KEY }}
          flags: "--max-instances=1 --use-http2 --port=9999 --platform=managed --allow-unauthenticated"
          env_vars: OPENAI_KEY=${{ secrets.OPENAI_KEY }},OPENAI_ORG=${{ secrets.OPENAI_ORG }}
          tag: ${{ env.version }}
      - 
        name: Echo URL
        run: echo "${{ steps.deploy.outputs.url }}"
      - 
        name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_REPOSITORY: louis030195/codex-code-translation