name: Build Docker images & push to Docker Hub

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            louis030195/codex-code-translation-server:latest
            louis030195/codex-code-translation-server:1.0.3
            ghcr.io/louis030195/codex-code-translation-server:latest
            ghcr.io/louis030195/codex-code-translation-server:1.0.3
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./client
          file: ./client/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            louis030195/codex-code-translation-client:latest
            louis030195/codex-code-translation-client:1.0.3
            ghcr.io/louis030195/codex-code-translation-client:latest
            ghcr.io/louis030195/codex-code-translation-client:1.0.3
